### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by sturple** [sturple/site-error-notifications#4]
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/cabox/workspa
ce/master/wp-content/plugins/site-error-notification/src/Fgms/SiteErrorNotifications/Utility.php on line 13  

https://github.com/sturple/site-error-notifications/blob/master/src/Fgms/SiteErrorNotifications/Utility.php#L13

(This is setup on codeanywhere under Fifthgeardev (dev) / master

**Comment by RobertLeahy** [comment]
Issue is `ErrorHandlerInterface::class`, not supported in 5.4 afaik.

**Comment by RobertLeahy** [comment]
Can change to `'\\Fgms\\SiteErrorNotifications\\ErrorHandlerInterface'`, since the above just resolves to that string.

**Comment by RobertLeahy** [comment]
Issue is now defunct as baa45997351b7a676624dfa3304a6ed11eab4789 changes the manner in which `\Fgms\SiteErrorNotifications\Utility::getBacktrace` detects the cut off for backtraces (it no longer uses `is_subclass_of` and therefore doesn't need to stringify any class names).
