### ISSUE TITLE
Error Logic - Report 500 or recover

### ISSUE THREAD

**Issue by sturple** [sturple/site-error-notifications#5]
Update error logic (E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
The only one that should halt the program is a Fatal error, if it can recover from error, then it needs to recover.

Should be a settings in config.yml that indicates what minimum level it reports.

**Comment by RobertLeahy** [comment]
This is pending 83475affc6e8009c1857348b22e9272ec2aa4685.

**Comment by sturple** [comment]
Hi @RobertLeahy 
Did you add this feature to the config.yml for minimum level and if so you need to add to README.md
with somthing like
level: {ERROR | WARNING | PARSE | NOTICE } of course use your coding conventions.

**Comment by RobertLeahy** [comment]
I haven't added any feature related to this to `config.yml`.  Currently this feature is just hardcoded to prevent the plugin from killing the PHP execution on the following error levels:
- `E_WARNING`
- `E_NOTICE`
- `E_CORE_WARNING`
- `E_COMPILE_WARNING`
- `E_USER_WARNING`
- `E_USER_NOTICE`
- `E_STRICT`
- `E_DEPRECATED`
- `E_USER_DEPRECATED`

If I were to add support to `config.yml` how should I go about it?  Do you want one configuration which simply prevents the script from dying?  One configuration which prevents all handling?  A configuration per error handling mechanism (i.e. one configuration to prevent the script from dying, one for emails, one for Monolog)?  Should there be a default if nothing is specified?

**Comment by RobertLeahy** [comment]
Do it separately.
